name: Executar Testes Automatizados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rodar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Instala as dependências (incluindo o @playwright/test)
      - name: Instalar dependências
        run: npm ci

      # Instala os navegadores e dependências de SO necessárias
      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps

      # Executa os testes
      - name: Rodar testes E2E com Playwright
        run: npm run test:e2e